version: '3'

services:
  db:
    image: postgres:14.1-alpine
    container_name: json_storage
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: strongPassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    

  web:
    image: node:14
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: strongPassword